#pragma once

#define RENDER_CHECK_SHADER_COMPILE  true
#define RENDER_CHECK_OPENGL_CALLS    true
#define RENDER_ENABLE_OPENGL_LOGGING true
#define RENDER_SHADER_LOG_SIZE       512

#define ENABLE_LOGGING true
